<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VAIBHAV-PC" ignored="0" name="ChromeTest" tests="1" failures="1" timestamp="07 Oct 2020 19:50:55 GMT" time="20.036" errors="0">
  <testcase name="@AfterMethod screenshotfail" time="0.005" classname="com.ibm.stax.BusinessLogic.BaseTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.ibm.stax.BusinessLogic.BaseTest.screenshotfail(BaseTest.java:105)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod screenshotfail -->
  <testcase name="@AfterClass Teardown" time="0.0" classname="com.ibm.stax.BusinessLogic.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterClass Teardown -->
  <testcase name="logintoapp" time="0.012" classname="com.ibm.stax.Tests.Login">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.ibm.stax.Tests.Login.logintoapp(Login.java:16)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- logintoapp -->
</testsuite> <!-- ChromeTest -->
